services:
  devcontainer:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app:cached
  app:
    build: .
    container_name: backend-container
    command: ./run.sh
    ports:
      - 8001:8001
    volumes:
      - .:/app